spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shiro2
    username: root
    password: ping1103
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: ForTest

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.entity
server:
  port: 9091

